### ISSUE TITLE
NCM autocompletion not working

### ISSUE THREAD

**Issue by fedeDev** [autozimu/LanguageClient-neovim#368]
- Summary:
Recent changes seem to have broken autocompletion with https://github.com/roxma/nvim-completion-manager. The last version which was working for me was https://github.com/autozimu/LanguageClient-neovim/commit/62371a88258066148f1a2ad5d85f5382785d35cf

- neovim version: 0.2.3-dev
- LanguageClient-neovim version: https://github.com/autozimu/LanguageClient-neovim/commit/1246c7e02e068fe0a90454e2da7825cb042fea03
- NCM version: https://github.com/roxma/nvim-completion-manager/commit/e724a442072261993ca503e969d2cb25722ab1d2

- My minimal vimrc
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

Plug 'roxma/nvim-completion-manager'

call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'cpp': [$HOME.'/build/cquery/build/release/bin/cquery',
    \ '--log-file=/tmp/cq.log'] } 
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_settingsPath =
	\ $HOME.'/.config/nvim/settings.json'
let g:LanguageClient_loggingLevel = 'DEBUG'
set completefunc=LanguageClient#complete
```
- test.cpp:
```c++ {.line-numbers}
int function() { return 1; }

int main() {
  fu|
  return 0;
}
```
- Reproduction steps:
    1. Open ```test.cpp``
    2. From within ```main``` stand in ```|``` 
    3. Type vim's autocompletion command: ```i_CTRL-X_CTRL-U``` -->autocompletion works!
    4. Keep typing (until ```func```) to trigger NCM
    5. NCM's autocompletion does not populate with LanguageClient's symbols.

- Log: https://gist.github.com/fedeDev/68469c4237b65023c50bc605a7dccfe6

This seems to be a problem when registering LSP as an autocompletion source for NCM. When using ```completefunc``` there is no issue with completions, so I don't include the cquery logs.

**Comment by autozimu** [comment]
Your downloaded binary is not up to date.

Try rerun `./install.sh` or `install.ps1`.

**Comment by kaijajan** [comment]
I encountered same issue. I believe 0.1.58 is the last version that auto completion works fine.
I removed LanguageClient-neovim folder locate in ~/.vim/plugged/ everytime I try a tagged version

```
rm -rf ~/.vim/plugged/LanguageClient-neovim
vi +PlugInstall +UpdateRemotePlugins +qa
```

```
Plug 'autozimu/LanguageClient-neovim', {
    \ 'tag': '0.1.xx',
    \ 'do': 'bash install.sh',
    \ }
```

And test with exactly the same code (live555 source code) and compile_commands.json.
cquery version: tag: v20180302
neovim version: 0.2.2

**Comment by fedeDev** [comment]
Thanks for chiming in @kaijajan! I tried his/her method as well and ```0.1.59``` is indeed the first version that breaks (where using ```i_CTRL-X_CTRL-U``` in fact results in an error, saying something like:  ```undefined reference to LanguageClient_omniComplete()```).

I tried re-running ```bash ./install.sh``` in the ```LanguageClient-neovim``` folder inside my ```~/.config/nvim/plugged``` directory. No luck, same results as before posted:
- Works with ```0.1.58```
- Does not work with anything  ```>= 0.1.59```

@autozimu how can the binary be "out of date"?

**Comment by autozimu** [comment]
I chanhed the log format days ago.

Your plugin version is almost up to date, but the log file you attached is
still the old one.

Please try update both the plugin and the binary to lastest, and attach the
log even if the same.

**Comment by mcesar** [comment]
I can confirm that this bug manifests with me too. I created a docker image (mcesar/lcn-bug368) that can be used for reproduction. The following recording shows the steps to reproduce the bug:
<a href="https://asciinema.org/a/X8MLH8JGZcO6rtlaWlyVI9FLH" target="_blank"><img src="https://asciinema.org/a/X8MLH8JGZcO6rtlaWlyVI9FLH.png" /></a>
Log: https://gist.github.com/mcesar/d14b4bded882a115604930a854ceab75

**Comment by fedeDev** [comment]
@automizu were you able to reproduce this. Seems  other people are also having it. 

I will gather logs for a more recent version, hopefully that will help you somehow. Even if the logs are old, I can assure you that versions after 0.1.58 are broken for me. However, the logs from @mcesar should suffice and be the same as mine.

Thanks for looking into this!

**Comment by autozimu** [comment]
Thanks for this bug report, especially the docker image for troubleshooting.

It might be because of my local cache, somehow I never experience this locally, nor can I reproduce it.

Sorry for the inconvenience and let me know if the latest changes didn't resolve.
